import Head from "next/head"
import React, { FunctionComponent } from "react"
import styled from "styled-components"
import { Footer } from "./Footer"
import { Header } from "./Header"
import { SkipToContent } from "./SkipToContent"

interface LayoutProps {}

const Main = styled.main`
  min-height: calc(100vh - 168px);
`

const Layout: FunctionComponent<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <html lang="en" />
        <title>accessibility workshop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <SkipToContent />
      <Header />
      <Main id="content">{children}</Main>
      <Footer />
    </>
  )
}

export default Layout
